FROM python:3.8

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /src

COPY src/requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY .env .env

COPY src/app app
COPY src/tests tests


CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]



